To host the slides, run

```bash
jupyter nbconvert ./JuliaPresentation.ipynb --to slides --post serve
```

# Julia: A Fresh Take on Scientific Computing

John Waczak 
04-07-2022

# About Me

- MI3NTS Research Group 
- Applied physics + ML for societal benefit
- Etc...

# Talk Outline

0. Motivating Example
1. Julia Overview
2. Julia Package Ecosystem
3. Jupyter and Pluto
4. Scientific Computing
5. $\partial$P: Differentiable Programming
6. Data Science / Machine Learning
7. High Performance Computing
8. Other Packages you should know about
9. Resources 


# Motivating Example: Neural ODEs

![Neural ODEs Paper](./figures/nodes_paper.png)


Looking closer at the code... 

![torchdiffeq 1](./figures/torchdiffeqex1.png)

To get the functionality we want, we have to reimplement standard ODE solvers on `Pytorch`'s tensor types. You can't just use `SciPy` solvers with `Numpy` arrays! 


**Wouldn't it be nice if disparate code bases developed by different teams just worked together?** 

# Enter Julia: A programming language by scientists, for scientists

<iframe src="https://julialang.org" title="The Julia Programming Language"></iframe>

# 1. Julia Overview

Julia is
- **Fast**: The JIT compiles your functions to native LLVM
- **Dynamically Typed**: develop your code quickly as you would in Python or R. 
- **Reproducible**: The powerful package manager makes reproducible environments a breeze. Package and hardware dependencies are tracked via `Project.toml` and `Manifest.toml` files
- **Composable**: Julia uses a *multiple-dispatch* paradigm allowing for effortless package composition
- **OPEN SOURCE** 


# Running Julia
There are two standard ways to run Julia: From a REPL (read-eval-print loop)

![Julia REPL](./figures/juliaREPL.png)


Or via the terminal, eg
```bash
$: julia my_script.jl
```

In [2]:
# some common julia operations: 

a = 1 
b = 2 
ϵ = 0.001

println(a+b)
println(a*b)
println((a-ϵ)/(b-ϵ))

3
2
0.4997498749374687


In [8]:
# "." syntax is used for broadcasting across vectors, matrices, etc... 

x = 0:(π/10):π  # i.e. linspace()

println(sin.(x))
println("\n")
println(exp.(x))

[0.0, 0.3090169943749474, 0.5877852522924731, 0.8090169943749475, 0.9510565162951535, 1.0, 0.9510565162951536, 0.8090169943749475, 0.5877852522924732, 0.3090169943749475, 1.2246467991473532e-16]


[1.0, 1.369107770624847, 1.8744560875853382, 2.566332395208135, 3.5135856242857333, 4.810477380965351, 6.586061962694725, 9.017028610942077, 12.345283939187368, 16.902024171711545, 23.140692632779267]


In [73]:
# some linear algebra examples

A = [1 3; 5 -9]
b = [1; 2]

x = A\b  # Solve linear system Ax = b

2-element Vector{Float64}:
 0.625
 0.125

In [30]:
display(A') # compute adjoint


B= [ 1 2+1im; -3 5-2im]
display(B)

display(B')

2×2 adjoint(::Matrix{Int64}) with eltype Int64:
 1   5
 3  -9

2×2 Matrix{Complex{Int64}}:
  1+0im  2+1im
 -3+0im  5-2im

2×2 adjoint(::Matrix{Complex{Int64}}) with eltype Complex{Int64}:
 1+0im  -3+0im
 2-1im   5+2im

# Julia Package Ecosystem
Packages in Julia can be included in code two different ways: 
- the `using` statement (add's packages functions to global namespace) 
- the `import` statement (python style restricted namespace) 

In [68]:
using LinearAlgebra
using DifferentialEquations
using Plots
using DataFrames  # Pandas-style data tables
using BenchmarkTools # for timing function calls

For packages you don't have installed, you can add the easily in the repl or by using the `Pkg` package

In [36]:
using Pkg
Pkg.add("Latexify") 

# see updated .toml files

    Updating registry at `~/.julia/registries/General.toml`
   Resolving package versions...
    Updating `~/gitrepos/presentations/julia/code/Project.toml`
  [23fbe1c1] + Latexify v0.15.14
  No Changes to `~/gitrepos/presentations/julia/code/Manifest.toml`


In [38]:
# Now we can add the package
using Latexify

latexify(A)

L"\begin{equation}
\left[
\begin{array}{cc}
1 & 3 \\
5 & -9 \\
\end{array}
\right]
\end{equation}
"

# Getting help

- Documentation in Julia is typically *pretty good*.
- Package specific documentation often found through link in github readme 
- From the repl (or jupyter) you can get help by typing `?` followed by the function name
- Docstrings use markdown allowing for nice styling, equation support, etc... 

In [39]:
?Transpose()

```
Transpose
```

Lazy wrapper type for a transpose view of the underlying linear algebra object, usually an `AbstractVector`/`AbstractMatrix`, but also some `Factorization`, for instance. Usually, the `Transpose` constructor should not be called directly, use [`transpose`](@ref) instead. To materialize the view use [`copy`](@ref).

This type is intended for linear algebra usage - for general data manipulation see [`permutedims`](@ref Base.permutedims).

# Examples

```jldoctest
julia> A = [3+2im 9+2im; 8+7im  4+6im]
2×2 Matrix{Complex{Int64}}:
 3+2im  9+2im
 8+7im  4+6im

julia> transpose(A)
2×2 transpose(::Matrix{Complex{Int64}}) with eltype Complex{Int64}:
 3+2im  8+7im
 9+2im  4+6im
```


# Creating Reproducible Projects 
The package system at the reple makes it easy to generate repoducbile programming envionments. 

![Pkg Demo](./figures/NewProject.mov)

- `Manifest.toml` and `Project.toml` will update as we add new dependencies
- We can then version control these files for easily reproducible envrionments 

# 3. Jupyter, Pluto, VSCode, and all that

There are many excellent ways to code in Julia from the standard Jupyter notebooks to the excellent VSCode extension. Pluto notebooks provide a unique reactive-style notebook exccelent for creating interactive documents and teaching resources.  

# Jupyter

- Julia has full support for Jupyter via the `IJulia` package (as you can see from these slides...)
- **NOTE** To add the Julia kernel to prexisting Jupyter installs, you may need to run `] build IJulia`

# Pluto 

![Plut demo](./figures/plutodemo.gif)

MIT has designed their **[Introduction to Computational Thinking](https://computationalthinking.mit.edu/Spring21/)** course around these notebooks. Check out these interactive Pluto notebooks!

![Intro Course](./figures/IntroCoursePage.mov)

# VSCode 

If you prefer working with scripts from an IDE, VSCode has an excellent extension

![VSCode Julia](./figures/VSCode.png)

...my personal preference is to use Emacs with vim keybindings ala `Spacemacs` 

![Spacemacs](./figures/spacemacs.png)

# 4. Scientific Computing in Julia

In [58]:
# Linear Alebra 
using LinearAlgebra

A = [1 2 3; 4 1 6; 7 8 1]
display(latexify(A))


# trace
display(tr(A))

# determinant
display(det(A))

# inverse
display(latexify(inv(A)))

# eigen-stuff 
display(eigen(A))

L"\begin{equation}
\left[
\begin{array}{ccc}
1 & 2 & 3 \\
4 & 1 & 6 \\
7 & 8 & 1 \\
\end{array}
\right]
\end{equation}
"

3

104.0

L"\begin{equation}
\left[
\begin{array}{ccc}
-0.4519230769230769 & 0.21153846153846154 & 0.08653846153846154 \\
0.3653846153846154 & -0.19230769230769232 & 0.05769230769230769 \\
0.24038461538461536 & 0.057692307692307696 & -0.0673076923076923 \\
\end{array}
\right]
\end{equation}
"

Eigen{Float64, Float64, Matrix{Float64}, Vector{Float64}}
values:
3-element Vector{Float64}:
 -6.214612641961068
 -1.554026596484783
 10.768639238445848
vectors:
3×3 Matrix{Float64}:
 -0.175709  -0.766257  -0.344989
 -0.570057   0.587185  -0.589753
  0.802596   0.26089   -0.730188

In [65]:
# there are lot's of convenient matrix factorizations 

display(factorize(A))  # LU is default unless your matrix is "nice" 

# a symmetric matrix
B = [1.5 2 -4; 2 -1 -3; -4 -3 5]
display(latexify(B))

factorize(B)

LU{Float64, Matrix{Float64}}
L factor:
3×3 Matrix{Float64}:
 1.0        0.0   0.0
 0.571429   1.0   0.0
 0.142857  -0.24  1.0
U factor:
3×3 Matrix{Float64}:
 7.0   8.0      1.0
 0.0  -3.57143  5.42857
 0.0   0.0      4.16

L"\begin{equation}
\left[
\begin{array}{ccc}
1.5 & 2.0 & -4.0 \\
2.0 & -1.0 & -3.0 \\
-4.0 & -3.0 & 5.0 \\
\end{array}
\right]
\end{equation}
"

BunchKaufman{Float64, Matrix{Float64}}
D factor:
3×3 Tridiagonal{Float64, Vector{Float64}}:
 -1.64286   0.0   ⋅ 
  0.0      -2.8  0.0
   ⋅        0.0  5.0
U factor:
3×3 UnitUpperTriangular{Float64, Matrix{Float64}}:
 1.0  0.142857  -0.8
  ⋅   1.0       -0.6
  ⋅    ⋅         1.0
permutation:
3-element Vector{Int64}:
 1
 2
 3

In [79]:
# if we know a matrix is "nice" in advance, we can tell the compiler so that 
# it can optimize behind the scenes for us 
sB = Symmetric(B)

@btime eigvals(B)
@btime eigvals(sB)

  729.478 ns (10 allocations: 1.69 KiB)
  705.950 ns (10 allocations: 1.69 KiB)


3-element Vector{Float64}:
 -2.310376890836094
 -1.1153277149900287
  8.925704605826123

In [86]:
(U,Σ,Vt) = svd(A)

SVD{Float64, Float64, Matrix{Float64}}
U factor:
2×2 Matrix{Float64}:
  0.213231  -0.977002
 -0.977002  -0.213231
singular values:
2-element Vector{Float64}:
 10.52622986305051
  2.280018611815189
Vt factor:
2×2 Matrix{Float64}:
 -0.443822   0.896115
 -0.896115  -0.443822

# DataFrames

- The `DataFrames.jl` package is the defacto package for dealing with Tabular data. 
- Julia packages are typically about separating distinct functionality (instead of behemoth packages) so, you'll need `CSV.jl` if you data is stored as .csv files. 

In [95]:
using DataFrames, CSV

df = DataFrame(CSV.File("./Iris.csv"))

display(df)

150×6 DataFrame
 Row │ Id     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Specie ⋯
     │ Int64  Float64        Float64       Float64        Float64       String ⋯
─────┼──────────────────────────────────────────────────────────────────────────
   1 │     1            5.1           3.5            1.4           0.2  Iris-s ⋯
   2 │     2            4.9           3.0            1.4           0.2  Iris-s
   3 │     3            4.7           3.2            1.3           0.2  Iris-s
   4 │     4            4.6           3.1            1.5           0.2  Iris-s
   5 │     5            5.0           3.6            1.4           0.2  Iris-s ⋯
   6 │     6            5.4           3.9            1.7           0.4  Iris-s
   7 │     7            4.6           3.4            1.4           0.3  Iris-s
   8 │     8            5.0           3.4            1.5           0.2  Iris-s
   9 │     9            4.4           2.9            1.4           0.2  Iris-s ⋯
  10 │    10            4.9           3.1            1.5           0.1  Iris-s
  11 │    11            5.4           3.7            1.5           0.2  Iris-s
  ⋮  │   ⋮          ⋮             ⋮              ⋮             ⋮               ⋱
 141 │   141            6.7           3.1            5.6           2.4  Iris-v
 142 │   142            6.9           3.1            5.1           2.3  Iris-v ⋯
 143 │   143            5.8           2.7            5.1           1.9  Iris-v
 144 │   144            6.8           3.2            5.9           2.3  Iris-v
 145 │   145            6.7           3.3            5.7           2.5  Iris-v
 146 │   146            6.7           3.0            5.2           2.3  Iris-v ⋯
 147 │   147            6.3           2.5            5.0           1.9  Iris-v
 148 │   148            6.5           3.0            5.2           2.0  Iris-v
 149 │   149            6.2           3.4            5.4           2.3  Iris-v
 150 │   150            5.9           3.0            5.1           1.8  Iris-v ⋯
                                                   1 column and 129 rows omitted