To host the slides, run

```bash
jupyter nbconvert ./JuliaPresentation.ipynb --to slides --post serve
```

# Julia: A Fresh Take on Scientific Computing 

John Waczak 
04-14-2022

# MINTS Research Group

![MINTS research group](./figures/MINTS_website.png)

# Talk Outline

0. Motivating Example
1. Julia Overview
2. Julia Package Ecosystem
3. IDEs and Notebooks 
4. Scientific Computing 
5. $\partial$P: Differentiable Programming 
6. Data Science and Machine Learning 
7. High Performance Computing 
8. Other Packages you should know about 
9. Resources 

# 0. Motivating Example: Neural ODEs

![Neural ODEs 1](./figures/nodes_paper.png)

![torchdiffeq 2](./figures/torchdiffeqex2.png)

So how do we actually implement this? I cant make Autodiff work with the ODE solvers from SciPy...

**(bad) Answer:** re-write ODE solvers using pytorch (or tensorflow) specialized tensor types. 

![Torchdiff code](./figures/torchdiffeqex1.png)

**Wouldn't it be nice if disparate code bases developed by different collobarations just worked together?** 

# Enter Julia: A programming language by scientists, for scientists

# 1. Julia Overview 

## 1.0 Why Julia? 

Julia is
- **Fast**: The JIT compiles your functions to native LLVM with speeds that rival Fortran and C
- **Dynamically Typed**: develop your code quickly as you would in Python or R. 
- **Reproducible**: The powerful package manager makes reproducible environments a breeze. Package and hardware dependencies are tracked via `Project.toml` and `Manifest.toml` files
- **Composable**: Julia uses a *multiple-dispatch* paradigm allowing for effortless package composition
- **OPEN SOURCE**: You won't need to enter wage slavery to afford a license for the software your dissertation is written in.  

Source: https://julialang.org/benchmarks/


![Benchmarks 1](./figures/benchmarks1.svg)

source: https://h2oai.github.io/db-benchmark/

![benchmarks 2](./figures/benchmarks2.png)

## 1.1 Installing Julia  


![Julia Downloads](./figures/julia_downloads.png)

benchmarks on network graphs: https://www.timlrx.com/blog/benchmark-of-popular-graph-network-packages-v2

![benchmarks 3](./figures/benchmarks3.webp)

differential equations and SciML benchmarks: https://github.com/SciML/SciMLBenchmarks.jl 

![Benchmark4a](./figures/benchmark4a.png)
![Benchmark4b](./figures/benchmark4b.png)

There are two standard ways to run Julia: 
1. Interactively in the REPL (read-eval-print loop) 
2. Via scripts

##  1.2 The Julia REPL

![Julia REPL](./figures/juliaREPL.png)

## 1.3 Running Scripts 

```bash
$: julia my_julia_script.jl
```

or 

```bash
$: julia --project=my_Project.toml my_julia_script.jl
```

## 1.4 Syntax

### 1.4.1 Variables

In [4]:
# Variables can be declared dynamically

X = 12 

12

In [5]:
test_string = "Hello world!"

"Hello world!"

In [6]:
vec = [1; 2; 3; 4; 5]

5-element Vector{Int64}:
 1
 2
 3
 4
 5

In [7]:
test_array = [ 1 2 3; 4 5 6; 7 8 9]

3×3 Matrix{Int64}:
 1  2  3
 4  5  6
 7  8  9

In [11]:
# we can use ANY valid unicode for variable names 
δ = 0.00001
😄 = 42 

😄 + δ

42.00001

### 1.4.2 Math

In [20]:
x = 10.0 
y = 32.0 

println("x+y = ", x+y)

println("x-y = ", x-y)

println("x*y = ", x*y)

println("x/y = ", x/y)

println("x^y = ", x^y)

println("y%x = ", y%x)  # remainder

x+y = 42.0
x-y = -22.0
x*y = 320.0
x/y = 0.3125
x^y = 1.0e32
y%x = 2.0


In [23]:
# math function are available by default
println("exp(x) = ", exp(x))
println("sin(x) = ", sin(x))
println("log(x) = ", log(x))

exp(x) = 22026.465794806718
sin(x) = -0.5440211108893698
log(x) = 2.302585092994046


### 1..4.3 Functions

In [24]:
# there are many ways to write functions in Julia! 

# standard: 
function f(x,y) 
    x + (1/3)y
end

f (generic function with 1 method)

In [25]:
f(2, 9)

5.0

In [27]:
# inline for Mathy oneliners 
f(x,y) = x + (1/3)y

f(2, 9)

5.0

In [28]:
# we can still use unicode characters for function names 
Σ(x, y) = x + y 
Σ(2, 3)

5

In [29]:
# further, we can use the `return` keyword for more complicated examples
function g(x,y) 
    return x*y 
    x+y 
end

g(2,3)

6

In [32]:
# we can tell the compiler the variable types for our arguments
function g(x::Int, word::String)
    println("Word: $(word), x: $(x)")
end

g(42, "test")

Word: test, x: 42


**NOTE**: Julia's attidue is that functions should be first class (not objects). 

- In linux, everything is a file
- In Julia, (*almost*) everything is a function

In [36]:
# operators are functions!

+(2.0, 10.0, 10.0, 20.0)

42.0

In [38]:
# we can do anymous functions as well 
map(x -> x^2 + 2x -1, 10.0)

119.0

### 1.4.4 Broadcasting

In [40]:
# we use "dot" syntax to broadcast functions across arrays, tuples, etc... 
x = ones(20)

f(ξ) = ξ + 0.1*rand()

# apply the func
f.(x)

20-element Vector{Float64}:
 1.0645590483743854
 1.038623725499053
 1.0291143701381171
 1.038899300907736
 1.070283166325028
 1.053078106883773
 1.061129525411541
 1.0730624744777697
 1.0172686682571426
 1.090164685329572
 1.0991764757649845
 1.0354158881852373
 1.0950182893013805
 1.0162532305532506
 1.0176052761603125
 1.0756175573054676
 1.0123555612798807
 1.0482119921764608
 1.030814057830626
 1.0762815175823088

# 1.4.5 Control Flow

## 1.5 Multiple Dispatch

### Julia's type system

### Multiple Dispatch is not Function Overloading

### Example 1: Forward Mode AD via Dual Numbers

### Example 2: Combining `Measurements.jl` with `DifferentialEquations.jl`. 
**You have no excuse to ignore uncuertainties!**

## 1.6 Loops are fast!

## 1.7 Metaprogramming

# 2. The Julia Package Ecosystem
*Reproducability made easy* 

## 2.1 The best part of the Julia ecosystem *really* is... 

![wtf am i reading](./figures/wtf_am_i_reading.png)

## The package manager! 

Modules in Julia can be included in code two different ways: 
- the `using` statement (add's packages functions to global namespace) 
- the `import` statement (python style restricted namespace)

`using` seems to be the standard choice

In [41]:
# ex 1: load the Package manager package: Pkg
using Pkg

In [43]:
# Add some packages
Pkg.add([
        "LinearAlgebra",
        "DifferentialEquations",
        "Plots",
        "DataFrames",
        "BenchmarkTools",
        "Latexify"
        ])

    Updating registry at `~/.julia/registries/General.toml`
   Resolving package versions...
    Updating `~/gitrepos/presentations/julia/code/Project.toml`
  [37e2e46d] + LinearAlgebra
  No Changes to `~/gitrepos/presentations/julia/code/Manifest.toml`


In [44]:
# load in the packages
using LinearAlgebra
using DifferentialEquations
using Plots
using DataFrames
using BenchmarkTools

┌ Info: Precompiling DifferentialEquations [0c46a032-eb83-5123-abaf-570d42b7fbaa]
└ @ Base loading.jl:1423


## 2.2 Defining project environments

Using the package manager in the REPL makes it easy to generate reproducible programming envrionments


![Pkg Demo](./figures/NewProject.mov)

- `Manifest.toml` and `Project.toml` will update as we add new dependencies
- We can then version control these files for easily reproducible envrionments 

## 2.3 Running your tests 

![run tests](./figures/runTests.mov)

## 2.4 Generating Documentation

- documentation can be built from your function docstrings via `Documenter.jl`

![documenter](./figures/documenter.png)

## 2.5 CI/CD via github workflows, travis, gitlab, etc.
are easy to set up via `PkgTemplates.jl` 

Example: build project on Julia version 1.7 and nightly and run tests. Then build docs and publish to github pages

![cicd](./figures/cicd.png)

## 2.6 Excellent Documentation Example: `DifferentialEquations.jl`

![diff eq docs](./figures/diffeqjldocs.png)

# 3. IDEs and Notebooks

## 3.1 VSCode Plugin

![VSCode Julia](./figures/VSCode.png)

## 3.2 But if you're crazy... use Spacemacs

![Spacemacs](./figures/spacemacs.png)

## 3.3 Jupyter Notebooks via `IJulia.jl`

## 3.4 Reactive programming with `Pluto.jl` notebooks 

![Plut demo](./figures/plutodemo.gif)

MIT has designed their **[Introduction to Computational Thinking](https://computationalthinking.mit.edu/Spring21/)** course around these notebooks. Check out these interactive Pluto notebooks!

![Intro Course](./figures/IntroCoursePage.mov)

# 4. Scientific Computing 

## 4.0 `LinearAlgebra.jl`

## 4.1 Working with Data: `DataFrames.jl`

## 4.2 Plotting with `Plots.jl` 

### 4.2.1 Backends, Commands, everything else you wanted to know

## 4.2.2 Plot Recipes: The greatest thing since sliced bread 

Use example of plots illustrative example of plots with measurements.jl... another cool example of multiple dispatch done right. 

## 4.3 DifferentialEquations.jl 

### 4.3.1 Syntax 

### 4.3.2 Benchmarks

### 4.3.3 PDE support

## 4.4 Leveraging metaprogramming for Domain Specific Languages

- ModelingToolkit 
- Catalyst.jl
- etc...

## 4.5 `Unitful.jl`

## 4.6 Julia-Python-Matlab Cheatsheet

## 4.7 Current Julia Projects
- Clima.jl 
- some sort of 

# 5. $\partial$P: Differentiable Programming

## 5.0 Functions are First Class! 

## 5.1 Automatic Differentiation + Multiple Dispatch = New Programming Paradigm 

## 5.2 Forward-Mode AD via `ForwardDiff.jl`

## 5.3 Reverse-Mode AD via `Zygote.jl`

## 5.3 Example: $\sqrt{x}$ Babylonian Algorithm

## 5.4 Jacobians and Hessians... Oh my! 

## 5.5 $\partial$P + Machine Learning = SciML

# 6. Data Science and Machine Learning in Julia

## 6.1 `Statistics.jl` 

## 6.2 `StatsPlots.jl`

## 6.3 `Flux.jl`

### 6.3.1 A simple Example

### 6.3.2 Neural Networks are Functions
- Show of Chain

### 6.3.3 Example Gallery

## 6.4 `MLJ.jl` a general machine learning framework

### 6.4.1 Scientific Types

### 6.4.2 Loading Models

### 6.4.3 Training Models 

### 6.4.4 Super-learners and general learning networks

## 6.5 Evaluating models with Shapely Values

## 6.6 Other useful ML examples (reinforcement learning, etc...) 

# 7. High Performance Computing

## 7.0 Benchmarking Julia code using `BenchmarkTools.jl`

## 7.1 General remarks of acheiving performance in Julia (see manual) 

### 7.1.2 Resource: Chris Rackauckas's class at MIT


## 7.2 Multi-threading in Julia 
- JULIA_NUM_THREADS environment variable
- Threads.@threads macro makes life easy! 

## 7.3 Optimizing Loops with `@inbounds` and `@simd`

## 7.4 Distribued computing with `Distributed.jl`

## 7.5 GPUS with `CUDA.jl` 

## 7.6 Loading the Julia module on HPC systems (Europa example) 

# 8. Other packages you should know about

## 8.1 Static site generation with `Franklin.jl` 

 - show picture of different available templates
 - show the MIT intro to computational thinking site

## 8.2 Literate programming with `Literate.jl`

## 8.3 Easy package generation with `PkgTemplates.jl`

## 8.4 `Graphs.jl` and associated packages 

- Plot network graphs 
- common graph theory functions 
- dispatches for generating graphs from other packages, e.g. catalyst.jl 

# 8.5 `Images.jl`
- array based image representation
- examples of color spaces 

## 8.5 Generating *nice* output with `Latexify.jl`

# 9. Resources for learning Julia
- Julia documentation (excellent!) 
- Downloading Julia
- MIT course on computational thinking
- Chris Rackauckas course 
- Talk Julia podcast
- Julia Discourse 
- Julia Slack channel (great for getting help; excellent community) 
- Julia Con youtube playlist